# Generated by Django 5.0 on 2023-12-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('subjects', models.CharField(choices=[('programin', 'برنامه\u200cنویسی'), ('languages', 'زبان\u200cهای خارجی'), ('it and softwere', 'آی\u200cتی و نرم\u200cافزار'), ('business management', 'مدیریت و کسب و کار'), ('finances', 'مالی و سرمایه\u200cگذاری'), ('uni:engineering', 'دانشگاهی: فنی و مهندسی'), ('uni:human sciences', 'دانشگاهی: علوم\u200cپایه، انسانی، پزشکی'), ('life hacks', 'مهارت\u200cهای زندگی'), ('art', 'هنر')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.main_learn')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Sub_Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.sub_learn')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('other_courses_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.sub_sub_learn')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teacher')),
            ],
        ),
    ]
