# Generated by Django 5.0 on 2023-12-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_learn',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='main_learn',
            name='name',
            field=models.CharField(choices=[('programin', 'برنامه\u200cنویسی'), ('languages', 'زبان\u200cهای خارجی'), ('it and softwere', 'آی\u200cتی و نرم\u200cافزار'), ('business management', 'مدیریت و کسب و کار'), ('finances', 'مالی و سرمایه\u200cگذاری'), ('uni:engineering', 'دانشگاهی: فنی و مهندسی'), ('uni:human sciences', 'دانشگاهی: علوم\u200cپایه، انسانی، پزشکی'), ('life hacks', 'مهارت\u200cهای زندگی'), ('art', 'هنر')], max_length=50),
        ),
    ]
