# Generated by Django 5.0 on 2023-12-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_main_learn_subjects_alter_main_learn_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_sub_learn',
            name='about',
        ),
    ]
