# Generated by Django 5.0 on 2023-12-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_sub_sub_learn_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_learn',
            name='name',
            field=models.CharField(choices=[('برنامه\u200cنویسی', 'برنامه\u200cنویسی'), ('زبان\u200cهای خارجی', 'زبان\u200cهای خارجی'), ('آی\u200cتی و نرم\u200cافزار', 'آی\u200cتی و نرم\u200cافزار'), ('مدیریت و کسب و کار', 'مدیریت و کسب و کار'), ('مالی و سرمایه\u200cگذاری', 'مالی و سرمایه\u200cگذاری'), ('دانشگاهی: فنی و مهندسی', 'دانشگاهی: فنی و مهندسی'), ('دانشگاهی: علوم\u200cپایه، انسانی، پزشکی', 'دانشگاهی: علوم\u200cپایه، انسانی، پزشکی'), ('مهارت\u200cهای زندگی', 'مهارت\u200cهای زندگی'), ('هنر', 'هنر')], max_length=50),
        ),
    ]
