# Generated by Django 5.0 on 2023-12-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_main_learn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='other_courses_needed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
