# Generated by Django 5.0 on 2023-12-17 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_other_courses_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='other_courses_needed',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
