# Generated by Django 4.2 on 2023-12-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_number_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nationalid', models.CharField(max_length=10)),
                ('seat', models.PositiveIntegerField()),
                ('reservation', models.CharField(max_length=8, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.teacher')),
            ],
        ),
    ]
