# Generated by Django 4.2 on 2023-12-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='flight',
            new_name='teacher',
        ),
    ]
