# Generated by Django 5.0 on 2023-12-27 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedBack_app', '0002_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 27, 18, 54, 30, 206376)),
        ),
    ]
